version: 2

mkdocs:
  fail_on_warning: true
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - "pip install poetry"
      - "poetry export --without-hashes --with=doc --format=requirements.txt > requirements_doc.txt"

    post_install:
      - "pip install -r requirements_doc.txt"