PRODUTO_ARRECADACAO = 8

SEGUIMENTO_PREFEITURA = 1
SEGUIMENTO_SANEAMENTO = 2
SEGUIMENTO_ENERGIA_ELETRICA_GAS = 3
SEGUIMENTO_TELECOMUNICACOES = 4
SEGUIMENTO_ORGAOS_GOVERNAMENTAIS = 5
SEGUIMENTO_DEMAIS = 6
SEGUIMENTO_MULTAS_TRANSITO = 7
SEGUIMENTO_EXCLUSIVO_BANCO = 9

MODULO10_VALOR_EFETIVO = 6
MODULO10_QUANTIDADE_MOEDA = 7
MODULO11_VALOR_EFETIVO = 8
MODULO11_QUANTIDADE_MOEDA = 9


def barcode():
    pass


if __name__ == '__main__':

    print('Ola mundo')
