name: "Febraban Barcode Pipeline"
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Ls
        run: echo $(ls -lah)
