name: "Febraban Barcode Pipeline"
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: echo $(python -V)

      - run: pip install poetry
      - run: poetry install --without doc
      - run: poetry run task test
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required